import { resolve } from 'node:path'

import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { doors, serves } from 'kehikot-module-protocol/serve'
import { defineConfig } from 'vite'

import { BUILD, MANIFEST, answer } from './doors.ts'
import { ID, PREFERRED_PORT } from './manifest.ts'

/**
 * The two style rules that live in the document rather than in the CSS, handed to the protocol's
 * `pageDocument` as its `head`.
 *
 * `height: 100%` on `html`, `body` and the root, and `overflow: hidden` on the body. A file is
 * something this page scrolls INTERNALLY: it takes the height it is given and scrolls inside it —
 * which requires that the height actually reach the scroll container. A default
 * `html { height: auto }` silently breaks that chain: the container measures zero and the file
 * appears to be empty with no error anywhere.
 *
 * `overflow: hidden` on the body is the standing rule of this workspace made literal: the BODY
 * never scrolls, in either direction. Everything that scrolls does so in a container inside it —
 * and this is the module where that matters most, because the thing on screen is lines of code
 * whose length nobody chose.
 */
const PAGE_HEAD = '<style>html, body, #root { height: 100%; } body { margin: 0; overflow: hidden; }</style>'

/**
 * The dev server, and the one line missing from it that matters most.
 *
 * ## `serves()` and `doors()`
 *
 * `serves()` decides the port from `PREFERRED_PORT` (or $PORT from a host) and keeps the
 * registration true, so there is no `server.port` here and no `--port` in `run.sh`.
 *
 * `doors()` is every door this app answers on, served by the one process that serves the page: the
 * manifest at both well-known paths, `/app` with the build printed into it (and no ticket — this
 * module has no writes), and `/healthz`, `/mcp` and `/api/*` through `answer` in doors.ts. A module
 * is ONE ORIGIN — the page fetches `/api/source` as a relative path — and `/app` has to be claimed
 * before Vite's resolver sees it, because this repository has a `src/app.tsx`. See the protocol's
 * docs/module-plumbing.md.
 *
 * ## No `server.cors` — this module declares storage instead
 *
 * Modules that hold nothing usually set `cors: true` and have to. A host frames a
 * module WITHOUT `allow-same-origin` unless its manifest declares storage, which
 * puts the page on an opaque origin — and `<script type="module">` is ALWAYS
 * fetched in CORS mode, so with no permissive header not one script in the page
 * runs. The document loads, `load` fires, the host greets it, and nothing
 * answers. `curl` cannot see it, being unsubject to CORS; only the browser
 * console can. That has cost this workspace days.
 *
 * This module must not go that way, for the worst reason any module here has. A
 * permissive `Access-Control-Allow-Origin` on this port means any page in any
 * tab can ask it for the CONTENTS of any file under any project on this machine,
 * and read the answer. The explorer's version of that hole leaks what your files
 * are called; this one leaks what they say.
 *
 * So the manifest declares `storage: true` and this line is absent. With a real
 * origin, this page's scripts and its `/api` calls are ordinary same-origin
 * requests: no CORS is involved at all and nothing is offered to strangers.
 *
 * ## No alias for `kehikot-module-protocol`
 *
 * There used to be one, in every app here, pointing at the protocol's source in
 * the repository they all used to live in. It must not come back: the package's
 * `exports` are correct, reaching past them is what made a whole class of bug
 * possible, and a module that resolved its contract differently from the host it
 * talks to is a module testing something nobody ships.
 *
 * The `@` alias below is a different thing entirely — it points inside this
 * repository, at `src`, and is what shadcn's generated components import through.
 *
 * ## There is no `build` script, and no `build` here worth having
 *
 * `run.sh` runs Vite. Nothing serves a `dist/`, so a build would produce a second
 * answer to "what does this page say" which disagrees with the first the moment
 * somebody edits `src/`. It also could not succeed: the page is generated by
 * `doors()` and there is no `index.html` for Rollup to start from.
 */
export default defineConfig({
  /**
   * `base: './'`, because this page is served at `/app` here and framed by a
   * host at whatever address that host wrote down. Absolute asset paths are
   * correct in the first case and a guess in the second; relative ones are a fact
   * in both, because the browser resolves them against the document it just
   * fetched.
   */
  base: './',
  plugins: [
    serves({ id: ID, prefer: PREFERRED_PORT }),
    doors({ manifest: MANIFEST, answer, build: BUILD, page: { title: 'Source', head: PAGE_HEAD } }),
    react(),
    tailwindcss(),
  ],
  resolve: { alias: { '@': resolve(import.meta.dirname, 'src') } },
})
